$wallpaperDir = $HOME/Pictures/wallpapers/on-display

$hpwp1 = $wallpaperDir/wallhaven-2y1d79.png
$hpwp2 = $wallpaperDir/wallhaven-lm2762.jpg 


preload = $hpwp1
preload = $hpwp2
#set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used
wallpaper = DP-1,$hpwp1
#if more than one monitor in use, can load a 2nd image
wallpaper = HDMI-A-1,$hpwp2
# .. more monitors

#enable splash text rendering over the wallpaper
splash = false

#fully disable ipc
# ipc = off

