windowrule=float,pavucontrol
windowrule=float,Wofi

windowrule=opacity 1.0,^(firefox)$
windowrule=opacity 0.96,^(Code)$
windowrulev2=opacity 0.96,class:discord
windowrule=opacity 0.95,^(wofi)$

windowrulev2 = float,class:^(org.kde.polkit-kde-authentication-agent-1)$
windowrulev2 = float,class:^(org.gnome.polkit-gnome-authentication-agent-1)$
windowrulev2 = float,class:^()$,title:^(Steam - Self Updater)$
windowrulev2 = float,class:(nm-connection-editor)

# windowrulev2 = tag +term,class:^(kitty)$,title:^(kitty)$
windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
windowrulev2 = center,class:^(kitty)$,title:^(kitty)$
windowrulev2 = size 50%,class:^(kitty)$,title:^(kitty)$
# windowrulev2 = workspace special:term,class:^(kitty)$,title:^(kitty)$

windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.
windowrulev2=opacity 1.0,class:.*,fullscreen:1 # Any fullscreen app will be completely opaque